Resolve merge conflicts from patch
error: error: while searching for:
error: patch failed: app/controllers/spree/admin/insights_controller.rb:44

[no-pt-story]